<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\PetHelper.Core\PetHelper.Core.csproj" />
      <ProjectReference Include="..\..\Shared\PetHelper.Framework\PetHelper.Framework.csproj" />
      <ProjectReference Include="..\PetHelper.Discussions.Contracts\PetHelper.Discussions.Contracts.csproj" />
      <ProjectReference Include="..\PetHelper.Discussions.Domain\PetHelper.Discussions.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    </ItemGroup>
    
</Project>
