<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\PetHelper.Core\PetHelper.Core.csproj" />
      <ProjectReference Include="..\..\Shared\PetHelper.SharedKernel\PetHelper.SharedKernel.csproj" />
      <ProjectReference Include="..\PetHelper.VolunteerRequests.Application\PetHelper.VolunteerRequests.Application.csproj" />
      <ProjectReference Include="..\PetHelper.VolunteerRequests.Domain\PetHelper.VolunteerRequests.Domain.csproj" />
    </ItemGroup> 

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    </ItemGroup>

</Project>
